{
 "title": "Fullstack Backend",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Heap usado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Peticiones por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latencia promedio (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[5m])) / sum(rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "promedio"
    }
   ]
  },
  {
   "title": "Conexiones activas Postgres (Hikari)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "activas" }
   ]
  }
 ]
}