springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.flyway.clean-disabled=true

server.error.include-stacktrace=never
server.error.include-message=never

logging.level.root=INFO
