springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.flyway.clean-disabled=true

server.error.include-stacktrace=never
server.error.include-message=never

management.endpoints.web.exposure.include=health,prometheus

logging.level.root=INFO
