CREATE TABLE revinfo (
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT,
    username VARCHAR(255)
);

CREATE TABLE products_aud (
    id            BIGINT      NOT NULL,
    rev           INTEGER     NOT NULL,
    revtype       SMALLINT,
    name          VARCHAR(150),
    sku           VARCHAR(50),
    description   TEXT,
    category      VARCHAR(50),
    price         NUMERIC(12, 2),
    quantity      INTEGER,
    minimum_stock INTEGER,
    status        VARCHAR(30),
    created_at    TIMESTAMP,
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(255),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_products_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

ALTER TABLE products ADD COLUMN created_by VARCHAR(255);
ALTER TABLE products ADD COLUMN updated_by VARCHAR(255);
